name: book_room
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  book:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: pip install selenium webdriver-manager packaging
      - name: Run the book study room script
        env: 
          CPP_USERNAME: ${{ secrets.CPP_USERNAME }}
          CPP_PASSWORD: ${{ secrets.CPP_PASSWORD }}
        run: python Github_Driver.py
